name: gnc_dao_envisagerapp
description: "A new Flutter project."

publish_to: "none"

version: 0.0.0+6

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  freezed_annotation: ^2.4.4
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  flex_color_scheme: ^8.0.1
  image_picker: ^1.1.2
  flutter_animate: ^4.5.0
  custom_refresh_indicator: ^4.0.1
  flutter_upgrade_version: ^1.1.6
  url_launcher: ^6.3.1
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/

  fonts:
    - family: Gothic_A1
      fonts:
        - asset: assets/fonts/Gothic_A1/GothicA1-Thin.ttf
          weight: 100
        - asset: assets/fonts/Gothic_A1/GothicA1-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Gothic_A1/GothicA1-Light.ttf
          weight: 300
        - asset: assets/fonts/Gothic_A1/GothicA1-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gothic_A1/GothicA1-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gothic_A1/GothicA1-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gothic_A1/GothicA1-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gothic_A1/GothicA1-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gothic_A1/GothicA1-Black.ttf
          weight: 900

    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
          weight: 100
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
          weight: 900
        - asset: assets/fonts/Urbanist/Urbanist-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Urbanist/Urbanist-BlackItalic.ttf
          weight: 900
          style: italic

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/icon2.png"
  remove_alpha_ios: true